# true_north/urls.py

from django.urls import path

from true_north import views

app_name = "true_north"
urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    # CoreValue CRUD
    path(
        "core-values/",
        views.CoreValueListView.as_view(),
        name="core-value-list",
    ),
    path(
        "core-values/create/",
        views.CoreValueCreateView.as_view(),
        name="core-value-create",
    ),
    path(
        "core-values/<int:pk>/",
        views.CoreValueDetailView.as_view(),
        name="core-value-detail",
    ),
    path(
        "core-values/<int:pk>/update/",
        views.CoreValueUpdateView.as_view(),
        name="core-value-update",
    ),
    path(
        "core-values/<int:pk>/delete/",
        views.CoreValueDeleteView.as_view(),
        name="core-value-delete",
    ),
    # Goal CRUD
    path(
        "goals/",
        views.GoalListView.as_view(),
        name="goal-list",
    ),
    path(
        "goals/create/",
        views.GoalCreateView.as_view(),
        name="goal-create",
    ),
    path(
        "goals/<int:pk>/",
        views.GoalDetailView.as_view(),
        name="goal-detail",
    ),
    path(
        "goals/<int:pk>/update/",
        views.GoalUpdateView.as_view(),
        name="goal-update",
    ),
    path(
        "goals/<int:pk>/delete/",
        views.GoalDeleteView.as_view(),
        name="goal-delete",
    ),
    # Milestone CRUD
    path(
        "milestones/",
        views.MilestoneListView.as_view(),
        name="milestone-list",
    ),
    path(
        "milestones/create/",
        views.MilestoneCreateView.as_view(),
        name="milestone-create",
    ),
    path(
        "milestones/<int:pk>/",
        views.MilestoneDetailView.as_view(),
        name="milestone-detail",
    ),
    path(
        "milestones/<int:pk>/update/",
        views.MilestoneUpdateView.as_view(),
        name="milestone-update",
    ),
    path(
        "milestones/<int:pk>/delete/",
        views.MilestoneDeleteView.as_view(),
        name="milestone-delete",
    ),
    # ValueAction CRUD
    path(
        "value-actions/",
        views.ValueActionListView.as_view(),
        name="value-action-list",
    ),
    path(
        "value-actions/create/",
        views.ValueActionCreateView.as_view(),
        name="value-action-create",
    ),
    path(
        "value-actions/<int:pk>/",
        views.ValueActionDetailView.as_view(),
        name="value-action-detail",
    ),
    path(
        "value-actions/<int:pk>/update/",
        views.ValueActionUpdateView.as_view(),
        name="value-action-update",
    ),
    path(
        "value-actions/<int:pk>/delete/",
        views.ValueActionDeleteView.as_view(),
        name="value-action-delete",
    ),
    # Send-email actions
    path(
        "core-values/<int:pk>/send-email/",
        views.CoreValueSendEmailView.as_view(),
        name="core-value-send-email",
    ),
    path(
        "core-values/<int:pk>/schedule/create/",
        views.CoreValueScheduleCreateView.as_view(),
        name="core-value-schedule-create",
    ),
    path(
        "core-values/<int:pk>/schedule/edit/",
        views.CoreValueScheduleEditView.as_view(),
        name="core-value-schedule-edit",
    ),
    path(
        "core-values/<int:pk>/schedule/delete/",
        views.CoreValueScheduleDeleteView.as_view(),
        name="core-value-schedule-delete",
    ),
    path(
        "core-values/<int:pk>/schedule/send/",
        views.CoreValueScheduleSendNowView.as_view(),
        name="core-value-schedule-send",
    ),
    path(
        "goals/<int:pk>/send-email/",
        views.GoalSendEmailView.as_view(),
        name="goal-send-email",
    ),
    path(
        "goals/<int:pk>/schedule/create/",
        views.GoalScheduleCreateView.as_view(),
        name="goal-schedule-create",
    ),
    path(
        "goals/<int:pk>/schedule/edit/",
        views.GoalScheduleEditView.as_view(),
        name="goal-schedule-edit",
    ),
    path(
        "goals/<int:pk>/schedule/delete/",
        views.GoalScheduleDeleteView.as_view(),
        name="goal-schedule-delete",
    ),
    path(
        "goals/<int:pk>/schedule/send/",
        views.GoalScheduleSendNowView.as_view(),
        name="goal-schedule-send",
    ),
    path(
        "milestones/<int:pk>/send-email/",
        views.MilestoneSendEmailView.as_view(),
        name="milestone-send-email",
    ),
    path(
        "milestones/<int:pk>/schedule/create/",
        views.MilestoneScheduleCreateView.as_view(),
        name="milestone-schedule-create",
    ),
    path(
        "milestones/<int:pk>/schedule/edit/",
        views.MilestoneScheduleEditView.as_view(),
        name="milestone-schedule-edit",
    ),
    path(
        "milestones/<int:pk>/schedule/delete/",
        views.MilestoneScheduleDeleteView.as_view(),
        name="milestone-schedule-delete",
    ),
    path(
        "milestones/<int:pk>/schedule/send/",
        views.MilestoneScheduleSendNowView.as_view(),
        name="milestone-schedule-send",
    ),
    path(
        "value-actions/<int:pk>/send-email/",
        views.ValueActionSendEmailView.as_view(),
        name="value-action-send-email",
    ),
    path(
        "value-actions/<int:pk>/schedule/create/",
        views.ValueActionScheduleCreateView.as_view(),
        name="value-action-schedule-create",
    ),
    path(
        "value-actions/<int:pk>/schedule/edit/",
        views.ValueActionScheduleEditView.as_view(),
        name="value-action-schedule-edit",
    ),
    path(
        "value-actions/<int:pk>/schedule/delete/",
        views.ValueActionScheduleDeleteView.as_view(),
        name="value-action-schedule-delete",
    ),
    path(
        "value-actions/<int:pk>/schedule/send/",
        views.ValueActionScheduleSendNowView.as_view(),
        name="value-action-schedule-send",
    ),
    # CoreValue Email Schedules
    path(
        "core-value-email-schedules/",
        views.CoreValueEmailScheduleListView.as_view(),
        name="corevalue-email-schedule-list",
    ),
    path(
        "core-value-email-schedules/create/",
        views.CoreValueEmailScheduleCreateView.as_view(),
        name="corevalue-email-schedule-create",
    ),
    path(
        "core-value-email-schedules/<int:pk>/update/",
        views.CoreValueEmailScheduleUpdateView.as_view(),
        name="corevalue-email-schedule-update",
    ),
    path(
        "core-value-email-schedules/<int:pk>/delete/",
        views.CoreValueEmailScheduleDeleteView.as_view(),
        name="corevalue-email-schedule-delete",
    ),
    path(
        "core-value-email-schedules/<int:pk>/send-now/",
        views.CoreValueEmailScheduleSendNowView.as_view(),
        name="corevalue-email-schedule-send-now",
    ),
]
