# Generated by Django 4.1.7 on 2026-02-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("true_north", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="true_north.corevalue",
            ),
        ),
    ]
