# Generated by Django 6.0.3 on 2026-03-29 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_north', '0003_rename_task_valueaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValueEmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('frequency', models.CharField(choices=[('twice_daily', 'Twice a day (every 12 hours)'), ('daily', 'Once a day'), ('three_per_week', 'Three times a week (every 2 days)'), ('weekly', 'Once a week'), ('biweekly', 'Every two weeks'), ('monthly', 'Once a month')], default='daily', help_text='How often to receive a reminder email for this Core Value.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause this reminder without deleting it.')),
                ('next_send', models.DateTimeField(blank=True, help_text='When the next reminder email will be sent.', null=True)),
                ('last_sent', models.DateTimeField(blank=True, help_text='When the most recent reminder email was sent.', null=True)),
                ('core_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='true_north.corevalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corevalue_email_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Core Value Email Schedule',
                'verbose_name_plural': 'Core Value Email Schedules',
                'ordering': ('-created',),
            },
        ),
    ]
