# Generated by Django 4.1.7 on 2026-04-19 14:21

from django.db import migrations, models


def _normalize_scoped_orders(apps, schema_editor):
    CoreValue = apps.get_model("true_north", "CoreValue")
    Goal = apps.get_model("true_north", "Goal")
    Milestone = apps.get_model("true_north", "Milestone")
    ValueAction = apps.get_model("true_north", "ValueAction")

    for user_id in CoreValue.objects.values_list("user_id", flat=True).distinct():
        for index, obj in enumerate(
            CoreValue.objects.filter(user_id=user_id).order_by("order", "id")
        ):
            CoreValue.objects.filter(pk=obj.pk).update(order=index)

    for user_id, value_id in Goal.objects.values_list("user_id", "value_id").distinct():
        for index, obj in enumerate(
            Goal.objects.filter(user_id=user_id, value_id=value_id).order_by(
                "order", "id"
            )
        ):
            Goal.objects.filter(pk=obj.pk).update(order=index)

    for user_id, goal_id in Milestone.objects.values_list(
        "user_id", "goal_id"
    ).distinct():
        for index, obj in enumerate(
            Milestone.objects.filter(user_id=user_id, goal_id=goal_id).order_by(
                "order", "id"
            )
        ):
            Milestone.objects.filter(pk=obj.pk).update(order=index)

    for user_id, milestone_id in ValueAction.objects.values_list(
        "user_id", "milestone_id"
    ).distinct():
        for index, obj in enumerate(
            ValueAction.objects.filter(
                user_id=user_id,
                milestone_id=milestone_id,
            ).order_by("order", "id")
        ):
            ValueAction.objects.filter(pk=obj.pk).update(order=index)


class Migration(migrations.Migration):

    dependencies = [
        ("true_north", "0006_scheduled_task_users_group"),
    ]
    atomic = False

    operations = [
        migrations.RunPython(_normalize_scoped_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="corevalue",
            constraint=models.UniqueConstraint(
                fields=("user", "order"),
                name="true_north_corevalue_unique_order_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("value__isnull", False)),
                fields=("user", "value", "order"),
                name="true_north_goal_unique_order_per_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("value__isnull", True)),
                fields=("user", "order"),
                name="true_north_goal_unique_order_without_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                fields=("user", "goal", "order"),
                name="true_north_milestone_unique_order_per_goal",
            ),
        ),
        migrations.AddConstraint(
            model_name="valueaction",
            constraint=models.UniqueConstraint(
                fields=("user", "milestone", "order"),
                name="true_north_valueaction_unique_order_per_milestone",
            ),
        ),
    ]
