# Generated by Django 4.1.7 on 2025-12-18 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_project_asset_primary_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('idea', 'Idea'), ('todo', 'To-Do'), ('question', 'Question'), ('bug', 'Bug/Issue'), ('note', 'Note')], default='idea', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('done', 'Done'), ('dropped', 'Dropped')], default='new', max_length=10)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='core.workspace')),
            ],
        ),
    ]
