# Generated by Django 6.0.7 on 2026-07-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(blank=True, default='', help_text='The event ID assigned by Google Calendar.', max_length=255)),
                ('summary', models.CharField(help_text='The title/summary of the event (required by Google Calendar).', max_length=255)),
                ('start_datetime', models.DateTimeField(help_text='Start date and time of the event.')),
                ('end_datetime', models.DateTimeField(help_text='End date and time of the event.')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description/notes for the event.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_uri', models.TextField(blank=True, default='')),
                ('client_id', models.TextField(blank=True, default='')),
                ('client_secret', models.TextField(blank=True, default='')),
                ('scopes', models.TextField(blank=True, default='', help_text='Space-separated list of granted OAuth2 scopes.')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Credentials',
                'verbose_name_plural': 'Google Calendar Credentials',
            },
        ),
    ]
