# Generated by Django 4.1.7 on 2026-06-01 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import money_wise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this account (e.g. 'Chase Checking').", max_length=200)),
                ('institution', models.CharField(help_text='Bank or financial institution name.', max_length=200)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], default='checking', max_length=20)),
                ('account_number_last4', models.CharField(blank=True, help_text='Last 4 digits of the account number.', max_length=4)),
                ('routing_number', models.CharField(blank=True, help_text='Routing number (optional).', max_length=20)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code, e.g. USD.', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(help_text='CSV file exported from your bank.', upload_to=money_wise.models.csv_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='money_wise.bankaccount')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date.')),
                ('post_date', models.DateField(blank=True, help_text='Settlement / posting date.', null=True)),
                ('description', models.CharField(help_text='Merchant or transaction description.', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, Negative = debit.', max_digits=12)),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('interest', 'Interest'), ('other', 'Other')], default='debit', max_length=20)),
                ('category', models.CharField(blank=True, help_text="Category assigned by bank or user (e.g. 'Groceries').", max_length=200)),
                ('memo', models.TextField(blank=True, help_text='Additional memo or notes.')),
                ('check_number', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference / confirmation number.', max_length=100)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Running account balance after this transaction.', max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money_wise.bankaccount')),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
    ]
