# Generated by Django 4.1.7 on 2026-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_wise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='transactionupload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='transactionupload',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated'),
        ),
    ]
