# Generated by Django 4.1.7 on 2026-06-09 16:45

from django.db import migrations, models
import django.db.models.deletion
import money_wise.models


class Migration(migrations.Migration):

    dependencies = [
        ("money_wise", "0002_alter_bankaccount_created_alter_bankaccount_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image of your receipt.",
                        upload_to=money_wise.models.receipt_upload_path,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "purchased_on",
                    models.DateField(
                        blank=True,
                        help_text="Date shown on the receipt.",
                        null=True,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="money_wise.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
