# Generated by Django 4.1.7 on 2025-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pidevice",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Format: XX:XX:XX:XX:XX:XX",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="pidevice",
            name="ram",
            field=models.CharField(
                help_text="e.g., 500MB, .5GB, 2GB, 4GB, 8GB", max_length=50
            ),
        ),
    ]
