# Generated by Django 4.1.7 on 2026-03-16 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='A short name for this thought.', max_length=255, verbose_name='Name')),
                ('content', models.TextField(help_text='The main content of this thought.', verbose_name='Content')),
                ('realm', models.CharField(help_text='A label for the realm or category of this thought.', max_length=100, verbose_name='Realm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttr_thoughts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Thought',
                'verbose_name_plural': 'Thoughts',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='A short name for this thing.', max_length=255, verbose_name='Name')),
                ('content', models.TextField(help_text='The main content or description of this thing.', verbose_name='Content')),
                ('type', models.CharField(help_text='A label for the type or category of this thing.', max_length=100, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Thing',
                'verbose_name_plural': 'Things',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to send this reminder.', max_length=20, verbose_name='Frequency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reminder schedule is currently active.', verbose_name='Active')),
                ('next_send', models.DateTimeField(blank=True, help_text='When the next reminder will be sent.', null=True, verbose_name='Next Send')),
                ('last_sent', models.DateTimeField(blank=True, help_text='When the last reminder was sent.', null=True, verbose_name='Last Sent')),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='thing_thought_reminder.thing', verbose_name='Thing')),
                ('thought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='thing_thought_reminder.thought', verbose_name='Thought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reminder Schedule',
                'verbose_name_plural': 'Reminder Schedules',
                'ordering': ('-created',),
            },
        ),
    ]
