# Generated by Django 4.1.7 on 2025-04-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("care_craft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
    ]
