# Generated by Django 4.1.7 on 2025-06-01 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("care_craft", "0002_alter_activity_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareCraftNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of this note.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The content of this note.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="A reference URL for this note.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Add an image for the note.",
                        null=True,
                        upload_to="test_uploads/",
                        verbose_name="Main Image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_craft_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Care Craft Note",
                "verbose_name_plural": "Care Craft Notes",
                "ordering": ["-created"],
            },
        ),
    ]
