# Generated by Django 4.1.7 on 2024-12-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GoalRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("subgoal", "Subgoal"), ("supergoal", "Supergoal")],
                        max_length=50,
                    ),
                ),
                (
                    "child_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supergoals",
                        to="goals.goal",
                    ),
                ),
                (
                    "parent_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgoals",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent_goal", "child_goal")},
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="related_goals",
            field=models.ManyToManyField(
                related_name="related_to",
                through="goals.GoalRelationship",
                to="goals.goal",
            ),
        ),
    ]
