# Generated by Django 4.1.7 on 2024-12-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"verbose_name": "Goal", "verbose_name_plural": "Goals"},
        ),
        migrations.AlterModelOptions(
            name="goalrelationship",
            options={
                "verbose_name": "Goal Relationship",
                "verbose_name_plural": "Goal Relationships",
            },
        ),
    ]
