# Generated by Django 4.1.7 on 2024-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goalrelationship",
            options={
                "verbose_name": "Goal Relationship",
                "verbose_name_plural": "Goal Relationships",
            },
        ),
        migrations.AlterField(
            model_name="goalrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("goal_hierarchy", "Goal Hierarchy"),
                    ("task_hierarchy", "Task Hierarchy"),
                ],
                max_length=50,
            ),
        ),
    ]
