# Generated by Django 4.1.7 on 2024-12-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_alter_goal_options_alter_goalrelationship_options"),
        ("goals", "0002_alter_goalrelationship_options_and_more"),
    ]

    operations = []
