# Generated by Django 4.1.9 on 2023-08-24 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('text', models.TextField(help_text='The text of the bullet point.', max_length=500, verbose_name='Text')),
                ('user', models.ForeignKey(help_text='The user who created the bullet point.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Bullet Points',
            },
        ),
        migrations.CreateModel(
            name='ElevatorSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('theme', models.CharField(help_text='The theme of the elevator speech.', max_length=255, verbose_name='Theme')),
                ('text', models.TextField(help_text='The text of the elevator speech.', verbose_name='Text')),
                ('bullet_points', models.ManyToManyField(help_text='The bullet points that can be used in the elevator speech.', to='career_organizerator.bulletpoint', verbose_name='Bullet Points')),
                ('user', models.ForeignKey(help_text='The user who created the elevator speech.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Elevator Speeches',
            },
        ),
    ]
