# Generated by Django 4.1.7 on 2023-11-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("career_organizerator", "0002_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralInterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The text of the behavioral interview question.",
                        max_length=500,
                        verbose_name="Text",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the behavioral interview question.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Behavioral Interview Questions",
            },
        ),
    ]
