# Generated by Django 4.1.7 on 2023-11-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_organizerator", "0005_alter_questionresponse_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="behavioralinterviewquestion",
            name="text",
            field=models.TextField(
                help_text="The text of the behavioral interview question.",
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="bulletpoint",
            name="text",
            field=models.TextField(
                help_text="The text of the bullet point.", verbose_name="Text"
            ),
        ),
    ]
