# Generated by Django 4.1.7 on 2023-12-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_organizerator", "0007_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionresponse",
            name="summary",
            field=models.CharField(
                default="Temporary Summary",
                help_text="The summary of the question response.",
                max_length=500,
                verbose_name="Summary",
            ),
            preserve_default=False,
        ),
    ]
