# Generated by Django 4.1.7 on 2024-03-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_organizerator", "0008_questionresponse_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
