# Generated by Django 4.1.7 on 2023-08-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='language_framework_systems',
            field=models.ManyToManyField(help_text='The languages, frameworks, and systems used in the application.', related_name='applications', to='app_tracker.languageframeworksystem'),
        ),
        migrations.AlterField(
            model_name='application',
            name='testing_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='The relative amount of testing coverage for the application.', max_length=6),
        ),
        migrations.AlterField(
            model_name='djangomodel',
            name='description',
            field=models.TextField(help_text='The description of the Django model.'),
        ),
        migrations.AlterField(
            model_name='djangomodel',
            name='name',
            field=models.CharField(help_text='The name of the Django model.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='The content of the note.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='The title of the note.', max_length=255),
        ),
    ]
