# Generated by Django 4.1.7 on 2023-08-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0002_alter_application_language_framework_systems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='has_custom_user',
            field=models.BooleanField(default=False, help_text='Whether or not the application has a custom user model.'),
        ),
    ]
