# Generated by Django 4.1.7 on 2023-08-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0003_alter_application_has_custom_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='has_prod_deployment',
            field=models.BooleanField(default=False, help_text='Whether or not the application has a production deployment.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='has_sticky_footer',
            field=models.BooleanField(default=False, help_text='Whether or not the application has a sticky footer.'),
        ),
    ]
