# Generated by Django 4.1.7 on 2023-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0004_alter_application_has_prod_deployment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='repository_url',
            field=models.URLField(blank=True, help_text="The URL of the application's repository.", null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='testing_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='The relative amount of testing coverage for the application.', max_length=6, null=True),
        ),
    ]
