# Generated by Django 4.1.7 on 2023-08-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0005_alter_application_repository_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app_tracker.application'),
        ),
    ]
