# Generated by Django 4.1.9 on 2023-08-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0006_alter_note_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_email_sending',
            field=models.BooleanField(default=False, help_text='Whether or not the application had email sending capabilities (email settings in Config Vars)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='testing_level',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], help_text='The relative amount of testing coverage for the application.', max_length=6, null=True),
        ),
    ]
