# Generated by Django 4.1.9 on 2023-08-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0009_application_production_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_board_url',
            field=models.URLField(blank=True, help_text="The URL of the application's project board.", null=True),
        ),
    ]
