# Generated by Django 4.1.9 on 2023-08-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0011_application_is_template_repository_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='settings_in_dot_env_file',
            field=models.BooleanField(default=False, help_text="Whether or not the application's settings are in an environment file.", verbose_name='Settings in Environment File'),
        ),
    ]
