# Generated by Django 4.1.9 on 2023-08-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0012_application_settings_in_dot_env_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='settings_in_dot_yml_file',
            field=models.BooleanField(default=False, help_text="Whether or not the application's settings are in a YAML file.", verbose_name='Settings in YAML File'),
        ),
    ]
