# Generated by Django 4.1.9 on 2023-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0013_application_settings_in_dot_yml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether or not the application is a favorite.', verbose_name='Is Favorite'),
        ),
    ]
