# Generated by Django 4.1.9 on 2023-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0014_application_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='settings_in_environment',
            field=models.BooleanField(default=False, help_text="Whether or not the application's settings are in the environment.", verbose_name='Settings in Environment'),
        ),
    ]
