# Generated by Django 4.1.9 on 2023-08-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0015_application_settings_in_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_repository_url',
            field=models.URLField(blank=True, help_text="The URL of the application's reference repository.", null=True, verbose_name='Reference Repository URL'),
        ),
    ]
