# Generated by Django 4.1.9 on 2023-08-27 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tracker', '0016_application_reference_repository_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='The name of the project.', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='The description of the project.', null=True, verbose_name='Description')),
                ('owner', models.ManyToManyField(help_text='The owner(s) of the project.', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ManyToManyField(help_text='The project(s) that the application is associated with.', related_name='applications', to='app_tracker.project', verbose_name='Project'),
        ),
    ]
