# Generated by Django 4.1.9 on 2023-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0018_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_official_repository',
            field=models.BooleanField(default=False, help_text='Whether or not the application is a repository for an officialapp maintained by some other organization.', verbose_name='Is Official Repository'),
        ),
    ]
