# Generated by Django 4.1.7 on 2023-09-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0020_application_is_archive_repository_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='The name of the organizational concept.', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='The description of the organizational concept.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Organizational Concept',
                'verbose_name_plural': 'Organizational Concepts',
            },
        ),
    ]
