# Generated by Django 4.1.7 on 2023-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0022_organizationalconcept_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalconcept',
            name='applications',
            field=models.ManyToManyField(blank=True, help_text='The application(s) that the organizational concept is associated with.', to='app_tracker.application', verbose_name='Application(s)'),
        ),
    ]
