# Generated by Django 4.1.7 on 2023-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0023_alter_organizationalconcept_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="has_cicd",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the application has CI/CD.",
                verbose_name="Has CI/CD",
            ),
        ),
    ]
