# Generated by Django 4.1.7 on 2023-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0024_application_has_cicd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="has_cicd",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the application has CI/CD implemented.",
                verbose_name="Has CI/CD",
            ),
        ),
    ]
