# Generated by Django 4.1.7 on 2023-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0025_alter_application_has_cicd"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_simple_example",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the application is a simple example.",
                verbose_name="Is Simple Example",
            ),
        ),
    ]
