# Generated by Django 4.1.7 on 2023-09-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0026_application_is_simple_example"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the label.",
                        max_length=50,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "hue",
                    models.CharField(
                        blank=True,
                        help_text="The color of the label tag (e.g. '#2BDCC7', '#FF0000', 'ocre').",
                        max_length=25,
                        null=True,
                        verbose_name="Hue",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the label.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "application",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The application(s) that the label is associated with.",
                        null=True,
                        to="app_tracker.application",
                        verbose_name="Application(s)",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
