# Generated by Django 4.1.7 on 2023-09-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0027_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="application",
            field=models.ManyToManyField(
                blank=True,
                help_text="The application(s) that the label is associated with.",
                to="app_tracker.application",
                verbose_name="Application(s)",
            ),
        ),
    ]
