# Generated by Django 4.1.7 on 2023-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0028_alter_label_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="all_tests_passing",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not all tests are passing.",
                verbose_name="All Tests Passing",
            ),
        ),
    ]
