# Generated by Django 4.1.7 on 2023-09-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tracker", "0029_application_all_tests_passing"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="is_adapted_repository",
            field=models.BooleanField(
                default=False,
                help_text="Whether or not the application is a repository adapted from some other source.",
                verbose_name="Is Adapted Repository",
            ),
        ),
    ]
