# Generated by Django 4.1.7 on 2025-06-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0031_application_reference_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name and version of the operating system.",
                        max_length=100,
                        unique=True,
                        verbose_name="Operating System Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating System",
                "verbose_name_plural": "Operating Systems",
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "host_name",
                    models.CharField(
                        help_text="A unique host name for the server.",
                        max_length=100,
                        unique=True,
                        verbose_name="Host Name",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="The IP address of the server.",
                        null=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("test", "Test"),
                            ("development", "Development"),
                        ],
                        help_text="The environment this server belongs to (e.g., production, staging, test).",
                        max_length=50,
                        null=True,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the server (e.g., hardware specs, roles, etc.).",
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "applications",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Applications hosted on this server.",
                        related_name="servers",
                        to="app_tracker.application",
                        verbose_name="Applications",
                    ),
                ),
                (
                    "operating_system",
                    models.ForeignKey(
                        blank=True,
                        help_text="The OS running on this server.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_tracker.operatingsystem",
                        verbose_name="Operating System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Server",
                "verbose_name_plural": "Servers",
            },
        ),
    ]
