# Generated by Django 4.1.7 on 2025-06-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0032_operatingsystem_server"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatingsystem",
            options={
                "default_related_name": "operating_systems",
                "verbose_name": "Operating System",
                "verbose_name_plural": "Operating Systems",
            },
        ),
    ]
