# Generated by Django 4.1.7 on 2025-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0033_alter_operatingsystem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="form_factor",
            field=models.CharField(
                choices=[
                    ("Pi4", "Raspberry Pi 4"),
                    ("Pi5", "Raspberry Pi 5"),
                    ("PiZero", "Raspberry Pi Zero"),
                    ("PiPico", "Raspberry Pi Pico"),
                ],
                default="Pi4",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Format: XX:XX:XX:XX:XX:XX",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="name",
            field=models.CharField(
                default="temp-server-name", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="ram",
            field=models.CharField(
                default="4GB",
                help_text="e.g., 500MB, .5GB, 2GB, 4GB, 8GB",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
