# Generated by Django 4.1.7 on 2025-06-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0034_server_description_server_form_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="ram",
            field=models.CharField(
                blank=True,
                help_text="e.g., 500MB, .5GB, 2GB, 4GB, 8GB",
                max_length=50,
                null=True,
            ),
        ),
    ]
