# Generated by Django 4.1.7 on 2025-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0035_alter_server_ram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="server",
            options={
                "ordering": ["host_name"],
                "verbose_name": "Server",
                "verbose_name_plural": "Servers",
            },
        ),
        migrations.AddField(
            model_name="operatingsystem",
            name="code_name",
            field=models.CharField(
                blank=True,
                help_text="The code name of the operating system (e.g., Jammy Jellyfish).",
                max_length=100,
                null=True,
                verbose_name="Code Name",
            ),
        ),
    ]
