# Generated by Django 4.1.7 on 2025-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0036_alter_server_options_operatingsystem_code_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="form_factor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pi4", "Raspberry Pi 4"),
                    ("Pi5", "Raspberry Pi 5"),
                    ("PiZero", "Raspberry Pi Zero"),
                    ("PiPico", "Raspberry Pi Pico"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="host_name",
            field=models.CharField(
                blank=True,
                help_text="A unique host name for the server.",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Host Name",
            ),
        ),
    ]
