# Generated by Django 4.1.7 on 2025-08-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0037_alter_server_form_factor_alter_server_host_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Server",
            new_name="Host",
        ),
    ]
