# Generated by Django 4.1.7 on 2025-11-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0038_rename_server_host"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="host",
            options={
                "ordering": ["host_name"],
                "verbose_name": "Host",
                "verbose_name_plural": "Hosts",
            },
        ),
        migrations.AlterField(
            model_name="host",
            name="applications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Applications hosted on this host.",
                related_name="hosts",
                to="app_tracker.application",
                verbose_name="Applications",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("test", "Test"),
                    ("development", "Development"),
                ],
                help_text="The environment this host belongs to (e.g., production, staging, test).",
                max_length=50,
                null=True,
                verbose_name="Environment",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="host_name",
            field=models.CharField(
                blank=True,
                help_text="A unique host name for the host.",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Host Name",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="The IP address of the host.",
                null=True,
                verbose_name="IP Address",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about the host (e.g., hardware specs, roles, etc.).",
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="operating_system",
            field=models.ForeignKey(
                blank=True,
                help_text="The OS running on this host.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_tracker.operatingsystem",
                verbose_name="Operating System",
            ),
        ),
    ]
