# Generated by Django 4.1.7 on 2025-12-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0039_alter_host_options_alter_host_applications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="form_factor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pi5-8GB", "Raspberry Pi 5 - 8GB"),
                    ("Pi5-4GB", "Raspberry Pi 5 - 4GB"),
                    ("Pi5-2GB", "Raspberry Pi 5 - 2GB"),
                    ("Pi4-8GB", "Raspberry Pi 4 - 8GB"),
                    ("Pi4-4GB", "Raspberry Pi 4 - 4GB"),
                    ("Pi4-2GB", "Raspberry Pi 4 - 2GB"),
                    ("Pi4-1GB", "Raspberry Pi 4 - 1GB"),
                    ("Pi3B+", "Raspberry Pi 3 Model B+"),
                    ("Pi3B", "Raspberry Pi 3 Model B"),
                    ("Pi3A+", "Raspberry Pi 3 Model A+"),
                    ("PiZero2W", "Raspberry Pi Zero 2 W"),
                    ("PiZeroW", "Raspberry Pi Zero W"),
                    ("PiZero", "Raspberry Pi Zero"),
                    ("PiPico2W", "Raspberry Pi Pico 2 W"),
                    ("PiPico2", "Raspberry Pi Pico 2"),
                    ("PiPicoW", "Raspberry Pi Pico W"),
                    ("PiPico", "Raspberry Pi Pico"),
                    ("Desktop", "Desktop"),
                    ("Laptop", "Laptop"),
                    ("Server", "Server"),
                    ("Headless", "Headless Server"),
                    ("SwitchEth", "Switch - Ethernet"),
                    ("SwitchPOE", "Switch - Ethernet POE"),
                    ("Router", "Router"),
                    ("AccessPt", "Access Point"),
                    ("IoT", "IoT - General"),
                    ("Camera", "Camera"),
                    ("Sensor", "Sensor"),
                    ("VM", "Virtual Machine"),
                    ("Container", "Container"),
                    ("Cloud", "Cloud Instance"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
