# Generated by Django 4.1.7 on 2025-12-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0040_update_form_factor_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL address.",
                        max_length=2000,
                        verbose_name="URL",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="A short label or name for this URL.",
                        max_length=100,
                        verbose_name="Label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="An optional description of this URL.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "url_type",
                    models.CharField(
                        choices=[
                            ("documentation", "Documentation"),
                            ("repository", "Repository"),
                            ("api", "API"),
                            ("demo", "Demo/Preview"),
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("tutorial", "Tutorial"),
                            ("reference", "Reference"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="The type or category of this URL.",
                        max_length=20,
                        verbose_name="URL Type",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="The application that this URL is associated with.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="app_tracker.application",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["label"],
            },
        ),
    ]
