# Generated by Django 4.1.7 on 2025-12-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0041_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_pending_deployment',
            field=models.BooleanField(default=False, help_text='Whether or not the application is pending deployment to a server (e.g., packages like DuckDNS, Docker Engine, or Jenkins yet to be implemented on a server).', verbose_name='Is Pending Deployment'),
        ),
    ]
