# Generated by Django 4.1.7 on 2025-12-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_tracker", "0042_add_is_pending_deployment_to_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the host was paused or retired.",
                null=True,
                verbose_name="Archived At",
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("RETIRED", "Retired"),
                ],
                default="ACTIVE",
                help_text="The current status of the host (Active, Paused, or Retired).",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
