# Generated by Django 5.1.15 on 2026-07-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tracker', '0043_host_archived_at_host_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('Pi5-8GB', 'Raspberry Pi 5 - 8GB'), ('Pi5-4GB', 'Raspberry Pi 5 - 4GB'), ('Pi5-2GB', 'Raspberry Pi 5 - 2GB'), ('Pi4-8GB', 'Raspberry Pi 4 - 8GB'), ('Pi4-4GB', 'Raspberry Pi 4 - 4GB'), ('Pi4-2GB', 'Raspberry Pi 4 - 2GB'), ('Pi4-1GB', 'Raspberry Pi 4 - 1GB'), ('Pi3B+', 'Raspberry Pi 3 Model B+'), ('Pi3B', 'Raspberry Pi 3 Model B'), ('Pi3A+', 'Raspberry Pi 3 Model A+'), ('PiZero2W', 'Raspberry Pi Zero 2 W'), ('PiZero2WR10', 'Raspberry Pi Zero 2 W Rev 1.0'), ('PiZeroW', 'Raspberry Pi Zero W'), ('PiZero', 'Raspberry Pi Zero'), ('PiPico2W', 'Raspberry Pi Pico 2 W'), ('PiPico2', 'Raspberry Pi Pico 2'), ('PiPicoW', 'Raspberry Pi Pico W'), ('PiPico', 'Raspberry Pi Pico'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Server', 'Server'), ('Headless', 'Headless Server'), ('SwitchEth', 'Switch - Ethernet'), ('SwitchPOE', 'Switch - Ethernet POE'), ('Router', 'Router'), ('AccessPt', 'Access Point'), ('IoT', 'IoT - General'), ('Camera', 'Camera'), ('Sensor', 'Sensor'), ('VM', 'Virtual Machine'), ('Container', 'Container'), ('Cloud', 'Cloud Instance'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SSHConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('key_filename', models.CharField(blank=True, help_text='The filename of the SSH key (e.g., id_ed25519).', max_length=255, null=True, verbose_name='Key Filename')),
                ('key_comment', models.CharField(blank=True, help_text='The preferred comment used with the key (e.g., user@host).', max_length=255, null=True, verbose_name='Key Comment')),
                ('encryption_algorithm', models.CharField(choices=[('ed25519', 'Ed25519'), ('rsa', 'RSA'), ('ecdsa', 'ECDSA'), ('dsa', 'DSA')], default='ed25519', help_text='The encryption algorithm used for the key (e.g., ed25519).', max_length=20, verbose_name='Encryption Algorithm')),
                ('passphrase_protected', models.BooleanField(default=False, help_text='Whether the SSH key is protected by a passphrase.', verbose_name='Passphrase Protected')),
                ('client', models.ForeignKey(help_text='The client host that initiates the SSH connection.', on_delete=django.db.models.deletion.CASCADE, related_name='ssh_client_connections', to='app_tracker.host', verbose_name='Client')),
                ('server', models.ForeignKey(help_text='The server host that accepts the SSH connection.', on_delete=django.db.models.deletion.CASCADE, related_name='ssh_server_connections', to='app_tracker.host', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'SSH Connection',
                'verbose_name_plural': 'SSH Connections',
                'ordering': ['server', 'client'],
            },
        ),
    ]
