# Generated by Django 4.1.7 on 2023-03-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='statement',
            new_name='body',
        ),
    ]
