# Generated by Django 4.1.7 on 2023-03-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0002_rename_statement_statement_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
