# Generated by Django 4.1.7 on 2023-03-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0003_alter_statement_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='date_created',
            new_name='created',
        ),
    ]
