# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0004_rename_date_created_statement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
