# Generated by Django 4.1.7 on 2023-03-15 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0005_alter_statement_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statement',
            new_name='Inspirational',
        ),
    ]
