# Generated by Django 4.1.7 on 2023-03-15 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0006_rename_statement_inspirational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirational',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirationals', to=settings.AUTH_USER_MODEL),
        ),
    ]
