# Generated by Django 4.1.7 on 2023-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0007_alter_inspirational_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirational',
            name='body',
            field=models.CharField(help_text='Required. 500 characters or fewer.', max_length=500, verbose_name='Inspirational Body Text'),
        ),
    ]
