# Generated by Django 4.1.7 on 2023-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0008_alter_inspirational_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirational',
            name='body',
            field=models.TextField(help_text='Required.', verbose_name='Inspirational Body Text'),
        ),
    ]
