# Generated by Django 4.1.7 on 2023-08-18 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0009_alter_inspirational_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('beastie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inspirational', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boosts.inspirational')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
