# Generated by Django 4.1.7 on 2023-08-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0010_inspirationsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspirationsent',
            name='inspirational_text',
            field=models.TextField(default=1, verbose_name='Inspirational Text Sent to Beastie'),
            preserve_default=False,
        ),
    ]
