# Generated by Django 4.1.7 on 2023-09-08 23:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0011_inspirationsent_inspirational_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspirationsent',
            options={'verbose_name_plural': 'Inspirationals Sent'},
        ),
    ]
