# Generated by Django 4.1.7 on 2023-11-13 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0012_alter_inspirationsent_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspirationSent',
            new_name='InspirationalSent',
        ),
    ]
