# Generated by Django 4.1.7 on 2023-11-13 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boosts', '0013_rename_inspirationsent_inspirationalsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspirationalsent',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspirationals_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
