# Generated by Django 4.1.7 on 2025-05-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_it", "0002_alter_activity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylocation",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sublocations",
                to="plan_it.activitylocation",
            ),
        ),
    ]
