# Generated by Django 4.1.7 on 2025-05-19 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan_it", "0003_activitylocation_parent_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_snapshot", models.CharField(max_length=100)),
                ("type_name_snapshot", models.CharField(max_length=50)),
                (
                    "target_item_name_snapshot",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "activity_location_name_snapshot",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to original activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="plan_it.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
