# Generated by Django 4.1.7 on 2025-05-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_it", "0004_activityinstance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityinstance",
            options={
                "ordering": ["-completed_at"],
                "verbose_name": "Activity Instance",
                "verbose_name_plural": "Activity Instances",
            },
        ),
    ]
