# Generated by Django 4.1.7 on 2025-12-16 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="project",
        ),
        migrations.AddField(
            model_name="asset",
            name="primary_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_assets",
                to="assets.project",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="assets", to="assets.project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="next_action",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome",
            field=models.TextField(blank=True, help_text="What 'done' looks like."),
        ),
        migrations.AddField(
            model_name="project",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subprojects",
                to="assets.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("med", "Medium"), ("high", "High")],
                default="med",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("backlog", "Backlog"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("done", "Done"),
                    ("dropped", "Dropped"),
                    ("archived", "Archived"),
                ],
                default="inbox",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
