# Generated by Django 4.1.7 on 2025-11-29 02:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "expansion_label",
                    models.CharField(
                        help_text="E.g. 'Classic', 'Cataclysm', 'Battle for Azeroth'.",
                        max_length=64,
                    ),
                ),
                (
                    "max_skill",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional: max skill for this tier (e.g. 75, 150).",
                        null=True,
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="warcrafting.profession",
                    ),
                ),
            ],
            options={
                "ordering": ["profession__name", "expansion_label"],
                "unique_together": {("profession", "expansion_label")},
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "wow_class",
                    models.CharField(
                        choices=[
                            ("warrior", "Warrior"),
                            ("paladin", "Paladin"),
                            ("hunter", "Hunter"),
                            ("rogue", "Rogue"),
                            ("priest", "Priest"),
                            ("death_knight", "Death Knight"),
                            ("shaman", "Shaman"),
                            ("mage", "Mage"),
                            ("warlock", "Warlock"),
                            ("monk", "Monk"),
                            ("druid", "Druid"),
                            ("demon_hunter", "Demon Hunter"),
                            ("evoker", "Evoker"),
                        ],
                        help_text="Character class (Warrior, Mage, etc.).",
                        max_length=32,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("orc", "Orc"),
                            ("dwarf", "Dwarf"),
                            ("night_elf", "Night Elf"),
                            ("undead", "Undead"),
                            ("tauren", "Tauren"),
                            ("gnome", "Gnome"),
                            ("troll", "Troll"),
                            ("goblin", "Goblin"),
                            ("blood_elf", "Blood Elf"),
                            ("draenei", "Draenei"),
                            ("worgen", "Worgen"),
                            ("pandaren", "Pandaren"),
                        ],
                        help_text="Character race.",
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Current character level.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wow_characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Expansion-specific professions for this character.",
                        related_name="characters",
                        to="warcrafting.professiontier",
                    ),
                ),
            ],
            options={
                "ordering": ["owner__username", "name"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="E.g. 'Gold', 'Ashes of Al'ar', 'Timewarped Badge'.",
                        max_length=128,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("currency", "Currency"),
                            ("gear", "Gear"),
                            ("mount", "Mount"),
                            ("pet", "Pet"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="For GOLD, treat this as 'whole gold pieces'. For items, use count (e.g. 1 for a unique mount).",
                    ),
                ),
                (
                    "is_unique",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is meant to be a unique/soulbound thing.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (where it dropped, why it matters, etc.).",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="warcrafting.character",
                    ),
                ),
            ],
            options={
                "ordering": ["character__owner__username", "character__name", "name"],
                "unique_together": {("character", "name", "category")},
            },
        ),
    ]
