# Generated by Django 4.1.7 on 2025-12-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warcrafting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(
                choices=[
                    ("human", "Human"),
                    ("orc", "Orc"),
                    ("night_elf", "Night Elf"),
                    ("undead", "Undead"),
                    ("pandaren", "Pandaren"),
                ],
                help_text="Character race.",
                max_length=32,
            ),
        ),
    ]
