# Generated by Django 4.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warcrafting", "0002_alter_character_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(
                choices=[
                    ("human", "Human"),
                    ("orc", "Orc"),
                    ("night_elf", "Night Elf"),
                    ("undead", "Undead"),
                    ("tauren", "Tauren"),
                    ("troll", "Troll"),
                    ("gnome", "Gnome"),
                    ("dwarf", "Dwarf"),
                    ("blood_elf", "Blood Elf"),
                    ("draenei", "Draenei"),
                    ("goblin", "Goblin"),
                    ("worgen", "Worgen"),
                    ("pandaren", "Pandaren"),
                    ("void_elf", "Void Elf"),
                    ("lightforged_draenei", "Lightforged Draenei"),
                    ("highmountain_tauren", "Highmountain Tauren"),
                    ("nightborne", "Nightborne"),
                    ("dark_iron_dwarf", "Dark Iron Dwarf"),
                    ("maghar_orc", "Mag'har Orc"),
                    ("zandalari_troll", "Zandalari Troll"),
                    ("kul_tiran", "Kul Tiran"),
                    ("mechagnome", "Mechagnome"),
                    ("vulpera", "Vulpera"),
                    ("dracthyr", "Dracthyr"),
                    ("earthen", "Earthen"),
                ],
                help_text="Character race.",
                max_length=32,
            ),
        ),
    ]
