# Generated by Django 4.1.7 on 2025-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packing_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="activity",
        ),
        migrations.AddField(
            model_name="item",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="packing_list.activity"
            ),
        ),
    ]
