# Generated by Django 4.1.7 on 2026-02-15 15:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("true_north", "0002_alter_goal_value"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="ValueAction",
        ),
        migrations.RenameIndex(
            model_name="valueaction",
            new_name="true_north__user_id_12f1f6_idx",
            old_name="true_north__user_id_79e307_idx",
        ),
        migrations.RenameIndex(
            model_name="valueaction",
            new_name="true_north__user_id_e72ece_idx",
            old_name="true_north__user_id_a35889_idx",
        ),
        migrations.RenameIndex(
            model_name="valueaction",
            new_name="true_north__user_id_1c5345_idx",
            old_name="true_north__user_id_bfb694_idx",
        ),
    ]
