# Generated by Django 4.1.7 on 2026-04-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thought",
            options={
                "ordering": ("-created",),
                "verbose_name": "Thought",
                "verbose_name_plural": "Thoughts",
            },
        ),
    ]
