# Generated by Django 4.1.7 on 2024-03-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worksearchactivity",
            options={
                "verbose_name": "Work Search Activity",
                "verbose_name_plural": "Work Search Activities",
            },
        ),
    ]
