# Generated by Django 4.1.7 on 2025-12-18 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the reminder",
                        max_length=255,
                        verbose_name="Reminder Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the reminder",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this reminder is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this reminder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        help_text="How often to send the reminder",
                        max_length=20,
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Time of day to send the reminder",
                        verbose_name="Time",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week (for weekly frequency)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month (1-31, for monthly frequency)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this schedule is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated Celery Beat periodic task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_schedule",
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        help_text="Reminder to send",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="priority_deciderator.reminder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Schedule",
                "verbose_name_plural": "Reminder Schedules",
                "ordering": ["-created"],
            },
        ),
    ]
