# Generated by Django 4.1.7 on 2024-01-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unimportant_notes", "0002_rename_note_unimportantnote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unimportantnote",
            options={
                "ordering": ("-created",),
                "verbose_name": "Unimportant Note",
                "verbose_name_plural": "Unimportant Notes",
            },
        ),
    ]
