# Generated by Django 4.1.7 on 2024-01-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimportant_notes", "0003_alter_unimportantnote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="unimportantnote",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="A reference URL for this note.",
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="unimportantnote",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="The content of this note.",
                verbose_name="Content",
            ),
        ),
    ]
