# Generated by Django 4.1.7 on 2024-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimportant_notes", "0004_unimportantnote_url_alter_unimportantnote_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="unimportantnote",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Add an image for the note.",
                null=True,
                upload_to="test_uploads/",
                verbose_name="Main Image",
            ),
        ),
    ]
