# Generated by Django 4.1.7 on 2024-02-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimportant_notes", "0005_unimportantnote_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unimportantnote",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Add an image for the note.",
                null=True,
                upload_to="unimportant_notes/",
                verbose_name="Main Image",
            ),
        ),
    ]
