# Generated by Django 4.1.7 on 2024-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unimportant_notes", "0006_alter_unimportantnote_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of this tag.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note Tag",
                "verbose_name_plural": "Note Tags",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="unimportantnote",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for this note.",
                related_name="unimportant_notes",
                to="unimportant_notes.notetag",
                verbose_name="Tags",
            ),
        ),
    ]
