# Generated by Django 4.1.7 on 2024-04-04 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("unimportant_notes", "0007_notetag_unimportantnote_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetag",
            name="author",
            field=models.ForeignKey(
                default=1,
                help_text="The author of this tag.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
    ]
