# Generated by Django 4.1.7 on 2023-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the journal was last updated.'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the journal was created.'),
        ),
    ]
