# Generated by Django 4.1.7 on 2023-07-04 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_enquiry', '0003_growthopportunity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growthopportunity',
            options={'verbose_name': 'Growth Opportunity', 'verbose_name_plural': 'Growth Opportunities'},
        ),
        migrations.AlterField(
            model_name='growthopportunity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='growthopportunity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the growth opportunity was created.'),
        ),
        migrations.AlterField(
            model_name='growthopportunity',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time the growth opportunity was last updated.'),
        ),
    ]
