# Generated by Django 4.1.9 on 2023-08-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_enquiry', '0007_alter_journal_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthopportunity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='growthopportunity',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated'),
        ),
    ]
