# Generated by Django 4.1.7 on 2025-07-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Mark task as completed."
            ),
        ),
    ]
