# Generated by Django 4.1.7 on 2025-11-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["completed", "priority__level", "name", "created"]},
        ),
    ]
