# Generated by Django 4.1.7 on 2023-07-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('so_thankful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved_ones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
