# Generated by Django 4.1.7 on 2023-07-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so_thankful', '0002_lovedone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gratitude',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='lovedone',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='strength',
            old_name='owner',
            new_name='user',
        ),
    ]
