# Generated by Django 4.1.7 on 2023-07-27 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('systolic', models.PositiveSmallIntegerField(help_text='The systolic blood pressure reading.')),
                ('diastolic', models.PositiveSmallIntegerField(help_text='The diastolic blood pressure reading.')),
                ('user', models.ForeignKey(help_text='The user that measures their blood pressure.', on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blood Pressures',
            },
        ),
    ]
