# Generated by Django 4.1.7 on 2023-07-28 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('bpm', models.PositiveSmallIntegerField(help_text='The pulse reading.')),
                ('user', models.ForeignKey(help_text='The user that measures their pulse.', on_delete=django.db.models.deletion.CASCADE, related_name='pulses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pulse Measurement',
                'verbose_name_plural': 'Pulse Measurements',
            },
        ),
    ]
