# Generated by Django 4.1.7 on 2023-07-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_pulse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpressure',
            options={'verbose_name_plural': 'Blood Pressure Measurements'},
        ),
    ]
