# Generated by Django 4.1.7 on 2023-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0003_alter_bloodpressure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressure',
            name='diastolic',
            field=models.PositiveSmallIntegerField(help_text='The diastolic blood pressure reading.', verbose_name='Diastolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='systolic',
            field=models.PositiveSmallIntegerField(help_text='The systolic blood pressure reading.', verbose_name='Systolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='bpm',
            field=models.PositiveSmallIntegerField(help_text='The pulse rate in beats per minute.', verbose_name='Beats Per Minute'),
        ),
    ]
