# Generated by Django 4.1.7 on 2023-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0004_alter_bloodpressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='pulse',
            field=models.PositiveSmallIntegerField(default=0, help_text='The pulse rate in beats per minute.', verbose_name='Pulse'),
            preserve_default=False,
        ),
    ]
