# Generated by Django 4.1.7 on 2023-10-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vitals", "0006_temperature"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this object was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this object was last updated.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "measurement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The body weight measurement in pounds.",
                        max_digits=5,
                        verbose_name="Body Weight Measurement",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="The subject that gets their body weight measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_weights",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Body Weight Measurement",
                "verbose_name_plural": "Body Weight Measurements",
            },
        ),
    ]
