# Generated by Django 4.1.7 on 2025-08-17 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0007_bodyweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodpressure",
            name="diastolic",
            field=models.PositiveSmallIntegerField(
                help_text="The diastolic blood pressure reading.",
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(160),
                ],
                verbose_name="Diastolic Blood Pressure",
            ),
        ),
        migrations.AlterField(
            model_name="bloodpressure",
            name="pulse",
            field=models.PositiveSmallIntegerField(
                help_text="The pulse rate in beats per minute.",
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(220),
                ],
                verbose_name="Pulse",
            ),
        ),
        migrations.AlterField(
            model_name="bloodpressure",
            name="systolic",
            field=models.PositiveSmallIntegerField(
                help_text="The systolic blood pressure reading.",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(260),
                ],
                verbose_name="Systolic Blood Pressure",
            ),
        ),
        migrations.AddIndex(
            model_name="bloodpressure",
            index=models.Index(
                fields=["user", "-created"], name="vitals_bloo_user_id_e410ae_idx"
            ),
        ),
    ]
