# Generated by Django 4.1.7 on 2026-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0008_alter_bloodpressure_diastolic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressure',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes related to this blood pressure measurement.', verbose_name='Note'),
        ),
    ]
