# Generated by Django 4.1.7 on 2023-08-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CognativeDistortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='The name of the cognative distortion.', max_length=150, verbose_name='Cognative Distortion')),
                ('description', models.TextField(help_text='The description of the cognative distortion.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Cognative Distortion',
                'verbose_name_plural': 'Cognative Distortions',
                'ordering': ['name'],
            },
        ),
    ]
