# Generated by Django 4.1.7 on 2023-08-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='cognative_distortion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='cbt.cognativedistortion'),
        ),
    ]
