# Generated by Django 4.1.7 on 2023-08-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_thought_cognative_distortion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='cognative_distortion',
            field=models.ForeignKey(blank=True, help_text='The cognative distortion of the thought.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='cbt.cognativedistortion'),
        ),
    ]
