# Generated by Django 4.1.7 on 2023-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbt", "0007_remove_thought_cognative_distortion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thought",
            name="cognitive_distortion",
            field=models.ManyToManyField(
                blank=True,
                help_text="The cognitive distortion of the thought.",
                related_name="thoughts",
                to="cbt.cognitivedistortion",
            ),
        ),
    ]
