# Generated by Django 4.1.7 on 2026-04-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='Name of the storage location.', max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('room', 'Room'), ('cabinet', 'Cabinet'), ('shelf', 'Shelf'), ('drawer', 'Drawer'), ('box', 'Box'), ('bin', 'Bin'), ('closet', 'Closet'), ('garage', 'Garage'), ('attic', 'Attic'), ('basement', 'Basement'), ('other', 'Other')], default='other', help_text='Type of storage location.', max_length=100, verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this object was created.', verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date and time this object was last updated.', verbose_name='Updated')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('tool', 'Tool'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('document', 'Document'), ('food', 'Food'), ('book', 'Book'), ('toy', 'Toy'), ('sports', 'Sports Equipment'), ('kitchen', 'Kitchen Item'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', help_text='Type of item.', max_length=100, verbose_name='Type')),
                ('location', models.ForeignKey(blank=True, help_text='Where this item is stored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item_location.storagelocation', verbose_name='Storage Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('name',),
            },
        ),
    ]
