# Generated by Django 4.1.7 on 2025-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uc_goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
