# Generated by Django 4.1.7 on 2025-03-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uc_goals", "0002_goal_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Virtue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VIACharacterStrength",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "virtue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_strengths",
                        to="uc_goals.virtue",
                    ),
                ),
            ],
            options={
                "verbose_name": "VIA Character Strength",
                "verbose_name_plural": "VIA Character Strengths",
            },
        ),
    ]
