# Generated by Django 4.1.7 on 2025-03-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uc_goals", "0003_virtue_viacharacterstrength"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="character_strengths",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select character strengths associated with this goal.",
                related_name="goals",
                to="uc_goals.viacharacterstrength",
            ),
        ),
    ]
