# Generated by Django 4.1.7 on 2025-12-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_cabinet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="slug",
            field=models.SlugField(default="temp", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
