# Generated by Django 5.2.9 on 2025-12-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated URL-friendly identifier from name.', max_length=255, unique=True),
        ),
    ]
