# Generated by Django 5.2.9 on 2025-12-16 01:44

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Populate slugs for existing StockItem instances.
    """
    StockItem = apps.get_model('kanban_cabinet', 'StockItem')
    
    for item in StockItem.objects.filter(slug=''):
        base_slug = slugify(item.name)
        if not base_slug:
            base_slug = 'item'
        
        slug = base_slug
        counter = 2
        
        # Check for collision
        while StockItem.objects.filter(slug=slug).exclude(pk=item.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        item.slug = slug
        item.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """
    Clear slugs (reverse migration).
    """
    StockItem = apps.get_model('kanban_cabinet', 'StockItem')
    StockItem.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_cabinet', '0002_stockitem_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
