# Generated by Django 4.1.7 on 2025-12-16 01:36

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """
    Populate slug field for existing StockItem records.
    """
    StockItem = apps.get_model("kanban_cabinet", "StockItem")
    
    for item in StockItem.objects.all():
        base_slug = slugify(item.name)
        slug = base_slug
        counter = 2
        # Check for collisions
        while StockItem.objects.filter(slug=slug).exclude(pk=item.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        item.slug = slug
        item.save(update_fields=["slug"])


def reverse_populate_slugs(apps, schema_editor):
    """
    No reverse operation needed - slugs will be removed by reversing the AddField migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("kanban_cabinet", "0002_stockitem_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
