# Generated by Django 4.1.7 on 2025-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_cabinet', '0003_backfill_stockitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
