# Generated by Django 4.1.7 on 2024-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="notes",
            field=models.TextField(blank=True, help_text="Any notes for the activity."),
        ),
        migrations.AlterField(
            model_name="activitycompleted",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The date and time the activity was completed.",
            ),
        ),
    ]
