# Generated by Django 4.1.7 on 2024-02-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activity_tracker", "0002_alter_activity_notes_alter_activitycompleted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycompleted",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completed_activity",
                to="activity_tracker.activity",
            ),
        ),
    ]
