# Generated by Django 4.1.7 on 2024-03-09 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("activity_tracker", "0003_alter_activitycompleted_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycompleted",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time the activity was completed.",
            ),
        ),
    ]
